server:
  port: 8080
  servlet:
    context-path:
spring:
  mvc:
    static-path-pattern:
  jpa:
    hibernate:
      ddl-auto:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings

